feat(SFINT-3665): Add ability to select plugin on CA.js initialization.
coveo/coveo.analytics.js pull request #245
Opened 2021-01-07 23:54 UTC by louis-bompart

- Move plugin management into `plugin.ts`.
- (Very) strongly type the plugins stuff.
- Ensure retro-compatibility on init to avoid breaking changes.

Yet ToDo: Test

Opened as a draft PR to allow for early review ;)

2021-01-08 14:18 UTC, francoislg requested changes
The most important questions are related to the external plugins.

The rest is really nice, thanks for the tests refactor with fetchMock, way easier to understand!

2021-01-08 15:16 UTC, louis-bompart commented on src/coveoua/simpleanalytics.spec.ts
> +    (SVC as any)['Id'] = 'svc';
No because Id is a static property 😅

2021-01-08 15:26 UTC, dlafreniere commented on src/plugins/BasePlugin.ts
> +export type PluginOption = {client: AnalyticsClient; uuidGenerator?: typeof uuidv4};
`PluginOptions`

2021-01-08 17:14 UTC, louis-bompart commented on src/coveoua/plugins.ts
> -    register(name: string, plugin: any): void {
I'll probably take a leaf out of Google's book again and do something similar

I'll make sure we're mo' flexible and keep on allowing external plugins. This mean also that AvailablePluginNames interface will be axed because it won't have much sense after.

2021-01-08 22:08 UTC, louis-bompart commented on src/coveoua/plugins.ts
> +export type AvailablePluginsNames = keyof typeof pluginMap;
Will be removed because of the conclusion of this discussion https://github.com/coveo/coveo.analytics.js/pull/245/files/632dc3f98c9ebdd950cabc0fbb0735ea2774434f#r553934766

2021-01-11 20:24 UTC, francoislg commented on src/coveoua/plugins.ts
> +    private requiredPlugins: Partial<Record<string, Plugin>> = {};
why is it Partial?

2021-01-11 20:24 UTC, francoislg commented on src/coveoua/plugins.ts
> +    private registeredPluginsMap: Map<string, Plugin> = (() => {
Would this work instead? 
```
private registeredPluginsMap = {
 [EC.Id]: EC,
 [SVC.Id: SVC
}
```

2021-01-11 20:24 UTC, francoislg commented on src/coveoua/plugins.ts
> +        this.registeredPluginsMap.set(name, plugin);
:thinking: now that we have `require` mimicking `analytics.js`'s format, `register` is kind of confusing.

Maybe we could rename `register` to `provide` just like `analytics.js`? It was all internal anyway, so we might even be able to safely remove `register`

2021-01-11 20:24 UTC, francoislg commented on src/coveoua/plugins.ts
> +    unrequire(): void {
`clearRequired` ?

At first glance, I would think `unrequire` to be the opposite of `require` and take a `name` as a parameter :thinking:

2021-01-11 20:24 UTC, francoislg commented on src/coveoua/simpleanalytics.ts
> +    registerPlugin(name: string, plugin: Plugin) {
Should it be named `provide` to follow `analytics.js` ?

2021-01-12 19:51 UTC, louis-bompart commented on src/coveoua/plugins.ts
> +    unrequire(): void {
Yeah that was the idea at first. But, to decouple a plugin is too much of a hassle and I have to stop scope-creep somewhere 😅 .

2021-01-12 19:52 UTC, louis-bompart commented on src/coveoua/plugins.ts
> +    unrequire(): void {
(will rename)

2021-01-13 12:48 UTC, francoislg approved these changes
Great job, looks good!

I'd suggest waiting a bit before merging, I am currently trying to migrate to Jenkins and it doesn't currently publish new versions :thinking: 

Oh and you could bump the minor version right now!

2021-01-25 14:39 UTC, louis-bompart commented
👋 @dlafreniere can you run another pass so I can merge this :D

2021-01-27 16:05 UTC, dlafreniere approved these changes

2021-01-27 16:05 UTC, dlafreniere commented on src/coveoua/plugins.ts
> +    require(name: string, option: PluginOptions): void {
`option` -> `options`

2021-01-28 15:50 UTC, tedre191 approved these changes

2021-01-28 15:50 UTC, tedre191 commented on package.json
> +        "react-native": "^0.63.3",
Why do we have a dep. to react and react-native?

2021-01-28 15:52 UTC, merged

2021-01-28 15:55 UTC, louis-bompart commented on package.json
> +        "react-native": "^0.63.3",
#226