[SFINT-4408] Metadata sent updated in logSelectDocumentSuggestion and logSelectFieldSuggestion
coveo/coveo.analytics.js pull request #327
Opened 2022-02-21 15:02 UTC by mmitiche

### New properties need to be added to the metadata sent by logSelectDocumentSuggestion to report correctly the following events:
- Opening the Quickview of a document suggestion.
- Opening the document suggestion after clicking on its title from the Quickview.

### New property need to be added in the metadata sent by logSelectFieldSuggestion to report correctly the following event:

- Auto-selecting the classification with the highest confidence.

2022-02-21 15:41 UTC, lbergeron approved these changes
It looks good to me!

2022-02-21 18:55 UTC, erocheleau commented on src/caseAssist/caseAssistActions.ts
> +    openDocument?: boolean;
What's the difference between these two?

2022-02-21 19:04 UTC, erocheleau requested changes
Only test method that I would change and if you could explain what's the difference between the two parameters?

2022-02-21 19:04 UTC, erocheleau commented on src/caseAssist/caseAssistActions.ts
> +    openDocument?: boolean;
I think we should start documenting these interfaces? dunno if that's the standard, doesn't look like it is in this package...

2022-02-21 19:04 UTC, erocheleau commented on src/caseAssist/caseAssistClient.spec.ts
> +            ...(autoSelection && {autoSelection}),
I think I would prefer if the method set a default value and you were to change that value later in the test no?

```
const myFakeFieldSuggestion = fakeFieldSuggestion();
myFakeFieldSuggestion.autoSelection = true;
```

2022-02-21 19:04 UTC, erocheleau commented on src/caseAssist/caseAssistClient.spec.ts
> +    const fakeDocumentSuggestion = (fromQuickview?: boolean, openDocument?: boolean): DocumentSuggestion => {
Same as above, I would prefer that method to only set default and not take any parameter unless necessary.
Then you change the object received from that method.

2022-02-21 19:22 UTC, mmitiche commented on src/caseAssist/caseAssistActions.ts
> +    openDocument?: boolean;
fromQuickview property is set to true when the user opens the Quickview of a document suggestion and the openDocumentproperty is set to true when the user clicks on title of the document suggestion in the Quickview which  will trigger the opening of the document suggestion in a new tab.

2022-02-21 19:25 UTC, mmitiche commented on src/caseAssist/caseAssistClient.spec.ts
> +            ...(autoSelection && {autoSelection}),
Do you think this change will improve the clarity and the simplicity of the tests or there is another reason?

2022-02-23 20:03 UTC, erocheleau requested changes

2022-02-23 20:03 UTC, erocheleau commented on src/caseAssist/caseAssistActions.ts
> +    openDocument?: boolean;
I think we typically only differentiate between openQuickview or a regular click

1. Opening the quickview:
![image](https://user-images.githubusercontent.com/2488155/155398564-d4204d56-f7e1-48e7-ba18-bdcf90ad5eab.png)

2. Clicking on the title of the quickview:
![image](https://user-images.githubusercontent.com/2488155/155398639-8cb74ffa-e0f6-439b-9820-5a079966cd69.png)

3. clicking on the document title the normal way
![image](https://user-images.githubusercontent.com/2488155/155398695-0a57ffa1-0e54-40f5-9a93-cd9fbe7bc267.png)

2022-02-23 20:03 UTC, erocheleau commented on src/caseAssist/caseAssistActions.ts
> +    openDocument?: boolean;
So TL;DR, clicking on the title of the quickview document and clicking on the document itself to open, are both the same "event". Only opening the quickview should be different IMO

2022-02-23 20:38 UTC, erocheleau commented on src/caseAssist/caseAssistActions.ts
> +    openDocument?: boolean;
Misunderstanding, all is good :)

2022-02-23 20:38 UTC, erocheleau approved these changes

2022-02-23 20:40 UTC, mmitiche commented on src/caseAssist/caseAssistActions.ts
> +    openDocument?: boolean;
That's a small summary of the events we wanna capture:
we have the QuanticDocumentSuggestion component which is an accordion containing different document suggestions.

- when expanding a document suggestion we send a suggestion_click event without any additional property.
- when clicking the quickview button of a document suggestion  we send a suggestion_click event with the property fromQuickview set to true.
- when clicking on the title of the document suggestion in the Quickview, this will open the document suggestion in a new tab, we send a suggestion_click event with the property openDocument set to true.

2022-02-23 20:57 UTC, merged