fix: UA-7689 Convert product position and quantity to number if possible
coveo/coveo.analytics.js pull request #407
Opened 2023-04-13 14:48 UTC by aperron-coveo

While this is technically not a bug, it is much easier for us to do this rather than asking every customer to send numbers instead of strings in those fields.

This simply checks if product quantity and position are of type "number" and if not we try to convert it. If the result is not a number, we send the original string to the collect endpoint and get the appropriate error from the backend.

- [ ] Add tests

2023-04-13 14:50 UTC, lbourdages reviewed
Please add UTs 😄

2023-04-13 15:29 UTC, aperron-coveo commented on src/plugins/ec.ts
> +        if (Object.keys(product).indexOf('quantity') != -1 && typeof product.quantity != 'number') {
I'm not sure if it would be better here to do this instead
`Object.keys(product).indexOf('quantity') != -1 && typeof product.quantity === 'string'`
and then `// @ts-ignore` instead of casting as a string.

2023-04-13 18:09 UTC, aperron-coveo commented on src/plugins/ec.ts
> +        return updatedProduct;
I'm a bit confused about what the regex does in this. It seems to me that we can potentially replace user input with something else. For example, if the user passes 'abc', the regex replaces this by '' and then the `+` operator converts that to 0. Maybe we could just skip the conversion if it matches `[^\.\-0-9]`?

2023-04-13 18:13 UTC, aperron-coveo commented on src/plugins/ec.ts
> +        return updatedProduct;
```
private coerceToNumber(input: any): any {
    if (typeof input === 'string' && !input.match(/[^\.\-0-9]/) && input != '') {
        const value = +input;
        if (!isNaN(value)) {
            return value;
        }
    }
    return input;
}
```

2023-04-14 12:48 UTC, fvanham-coveo requested changes

2023-04-14 12:48 UTC, fvanham-coveo commented on src/plugins/ec.ts
> +        if (Object.keys(product).indexOf('quantity') != -1 && typeof product.quantity != 'number') {
Don't iterate all the keys. Just snipe the keys you are looking for (`quantity` and `position`):

2023-04-14 12:48 UTC, fvanham-coveo commented on src/plugins/ec.ts
> +    private convertNumberTypes(product: Product) {
missing return type?

2023-04-14 12:48 UTC, fvanham-coveo commented on src/plugins/ec.ts
> +        return updatedProduct;
The prefix argument is valid for currency type numbers only. We accept string values which include non-numeric prefix according to doc here: https://docs.coveo.com/en/l29e0540/coveo-for-commerce/commerce-coveo-ua-api-reference#currency
This does not apply to regular numbers like quantity and position. I would not do the regexes. If someone sends 💩 string they get 💩 string in the validation :)

2023-04-14 12:48 UTC, fvanham-coveo commented on src/plugins/ec.ts
> +        return updatedProduct;
A coerce function is a good idea, there's already a `utils.ts`. I'd make it so that a coerce on `undefined` just returns `undefined`, then you can blindly call `product.position = coerceToNumber(product.position)` in your main proc. If the key does not exist it won't be added.

2023-04-14 13:49 UTC, aperron-coveo commented on src/plugins/ec.ts
> +        return updatedProduct;
With the way I modified it, the regex checks for a char that is not a number or a `-` and if it matches anything, we just return the string. And for the "returning undefined" part, I'm pretty sure it would already work as is, so I'll remove the checks (`'quantity' in updatedProduct`) and move the coerce method to utils.ts

2023-04-14 13:51 UTC, rphilippen commented on src/plugins/ec.ts
> +        return updatedProduct;
Frank, just returning undefined and always setting it has the unfortunate side effect of **adding** a property, even if it wasn't specified. I don't think we should do that.

> If the key does not exist it won't be added.
That's not how JavaScript works:
```javascript
'product' in {product: undefined} === true
```

2023-04-14 14:49 UTC, rphilippen approved these changes

2023-04-14 17:16 UTC, fvanham-coveo commented on src/client/utils.ts
> +    if (typeof input === 'string' && input.match(/^-?\d*\.?\d+$/)) {
I don't think we need the (expensive) regex check here? Regardless, you're missing scientific notation numbers.

2023-04-14 17:16 UTC, fvanham-coveo commented on src/plugins/ec.spec.ts
> +        const validValues = ['13', '0', '.0', '-10', '5.0', '-1.1'];
This is preference, but I don't mind it if tests are not DRY. I now have to go to the test main func, find the called method, see what it does, wonder why you are deleting targets at the end. I came to the conclusion that that is because you are passing negative values into `position` due to reusing your test array and there's logic inside the library which removes that value, but only for position.

IMO I liked your first test setup way better. Could've done it with multiple products if you wanted a broader set of numbers.

2023-04-14 19:36 UTC, aperron-coveo commented on src/client/utils.ts
> +    if (typeof input === 'string' && input.match(/^-?\d*\.?\d+$/)) {
Do you have any idea other than with a regex to check if the input can be parsed?

2023-04-14 19:58 UTC, aperron-coveo commented on src/client/utils.ts
> +}
@rphilippen @fvanham-coveo this allows for numbers like `1.234e5` and `5.` to be converted. Its also much simpler than the regex

2023-04-17 08:25 UTC, fvanham-coveo approved these changes

2023-04-17 15:07 UTC, rphilippen approved these changes

2023-04-17 15:09 UTC, merged