fix(SFINT-4992): fix a crash in HistoryStore
coveo/coveo.analytics.js pull request #412
Opened 2023-04-25 20:00 UTC by erocheleau

[SFINT-4992](https://coveord.atlassian.net/browse/SFINT-4992)

For whatever reason, the value in `__coveo.analytics.history` in the localStorage when is valid JSON but NOT an array, makes the HistoryStore crash because it tries to call `.sort` and `.map` on something that isn't enforced to be an array.

I added safeguards against this, and a test to make sure it was covered.

[SFINT-4992]: https://coveord.atlassian.net/browse/SFINT-4992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-04-25 20:02 UTC, lbourdages approved these changes
Can this happen in normal operation, or just when someone messes with their local storage?

2023-04-25 20:04 UTC, tedre191 requested changes

2023-04-25 20:04 UTC, tedre191 commented on src/history.ts
> +        if (Array.isArray(currentHistory)) {
As this shouldn't happen unless something else is broken, and that is also mean that part of the feature will not work, we should add a warning in the console to let support, or the next person in maintenance, that will have to debug this in the future.

2023-04-25 20:06 UTC, erocheleau commented on src/history.ts
> +        if (Array.isArray(currentHistory)) {
I don't exactly know what the feature does, this is a HistoryClient used in the JSUI for example, so the JSUI handles what happens when the historyclient returns an empty array basically, and not the coveoua library

2023-04-28 14:04 UTC, erocheleau commented
> Can this happen in normal operation, or just when someone messes with their local storage?

We've had a support case because of some weird interaction inside Salesforce and their Locker Service, two localStorage keys had a collision basically. So some other data ended up in this localStorage key, which was valid JSON, but not an array.

And the crash from the lib was crashing the whole search page basically.

Overall I think it's best to make sure something is actually an array before trying to use Array functions on it :)

2023-04-28 17:50 UTC, tedre191 approved these changes

2023-04-28 17:50 UTC, merged