set trackingid from siteName and properties in customData
coveo/coveo.analytics.js pull request #431
Opened 2023-07-06 13:21 UTC by lucylu-coveo

2023-07-06 14:28 UTC, fvanham-coveo requested changes

2023-07-06 14:28 UTC, fvanham-coveo commented on functional/ec-events.spec.ts
> +    it('should be able to set trackingId with siteName', async () => {
These tests look good. I'd add a test that calls `await coveoua('send', 'view')` and verifies the element ends up in `customData` instead of the root, for both cases.

note: view is a UA event, pageview is a collect event.

2023-07-06 14:28 UTC, fvanham-coveo commented on src/client/analytics.spec.ts
> +    describe('with context_website is set in custom', () => {
This test still tests the incorrect condition: `custom` is not an officially supported key on `EventType.view`, that should read `customData`, but you've added these tests below I see. Even if this behavior currently works, it's not something we should encourage or ensure keeps working through a test.

2023-07-06 14:28 UTC, fvanham-coveo commented on src/client/analytics.spec.ts
> +        const trackingId = 'yourfavaritefood.ca ';
favorite

2023-07-06 14:28 UTC, fvanham-coveo commented on src/client/analytics.spec.ts
> +    describe('with siteName is set in custom', () => {
Same argument as above: `custom` is not a supported key on the event payload

2023-07-06 14:28 UTC, fvanham-coveo commented on src/client/analytics.spec.ts
> +            await client.sendEvent(EventType.view, {
I would also test this with a collect event (e.g. `EventType.pageview`) where the context_website is set on the root. If trackingId is not set, it should set it. If trackingId is also set it should not overwrite it.

2023-07-06 16:00 UTC, lucylu-coveo commented on src/client/analytics.spec.ts
> +    describe('with context_website is set in custom', () => {
this suite is testing this branch in setTrackingIdIfTrackingIdNotPresent:
```
        if (rest.hasOwnProperty('custom') && isObject(rest.custom)) {
            if (rest.custom.hasOwnProperty('context_website') || rest.custom.hasOwnProperty('siteName')) {
                rest['trackingId'] = rest.custom.context_website || rest.custom.siteName;
            }
        }
```

2023-07-07 02:09 UTC, lucylu-coveo commented on src/client/analytics.spec.ts
> +            await client.sendEvent(EventType.view, {
I'm not sure why we need to test context_website set on the root level? :thinking `trackingId` is only set with `context_website` in either `custom` or `customData` object. I have added the test as you suggested in my latest [commit](https://github.com/coveo/coveo.analytics.js/pull/431/commits/1d862cbfad63f11580d481eb271fb7575f88818c). It fails  as I expect 😛

2023-07-07 08:07 UTC, fvanham-coveo commented on src/client/analytics.spec.ts
> +            await client.sendEvent(EventType.view, {
Sorry, then the only way to set this for collect is by setting it as `coveoua('set', 'custom', {})`. My bad.

2023-07-07 08:10 UTC, fvanham-coveo commented on src/client/analytics.spec.ts
> +    describe('with context_website is set in custom', () => {
Yeah, but that branch is an officially unsupported case. `custom` is not a recognized event attribute on any event. It's a side effect of the original implementers injecting the `custom` properties on the event itself, rather than separating it out. If we add it as a test, that internal side-effect becomes sanctioned external behavior.

2023-07-07 08:13 UTC, fvanham-coveo approved these changes

2023-07-07 13:47 UTC, aperron-coveo approved these changes

2023-07-07 19:50 UTC, merged