feat(create article): UA event added for createArticle
coveo/coveo.analytics.js pull request #445
Opened 2023-11-21 21:11 UTC by SimonMilord

[SFINT-5276](https://coveord.atlassian.net/browse/SFINT-5276)

**The following custom event has been added to Insight Client for knowledge article creation:**

- createArticle

2023-11-21 21:43 UTC, erocheleau approved these changes
looks good

2023-11-21 21:43 UTC, erocheleau commented on src/searchPage/searchPageEvents.ts
> +    [InsightEvents.createArticle]: 'createArticle',
Is there any kind of order here? I would group it with the other InsightEvents :D

2023-11-21 21:44 UTC, SimonMilord commented on src/searchPage/searchPageEvents.ts
> +    [InsightEvents.createArticle]: 'createArticle',
I thought newer events at the bottom, but I can move it 😂

2023-11-22 12:14 UTC, mmitiche requested changes
In the Create Article event currently sent in the standard agent panel, the event contains the following custom data:

<img width="855" alt="Screenshot 2023-11-22 at 7 08 12 AM" src="https://github.com/coveo/coveo.analytics.js/assets/86681870/aa3a0fcd-8cfe-44fd-93ba-197e79350125">

Notice the fields `articleType` and `triggeredBy` are being sent in addition to the context.

Please consider adding these two fields to the metadata accepted by the `logCreateArticle` function added in this PR.

2023-11-22 14:10 UTC, erocheleau commented
> In the Create Article event currently sent in the standard agent panel, the event contains the following custom data:
> 
> <img alt="Screenshot 2023-11-22 at 7 08 12 AM" width="855" src="https://user-images.githubusercontent.com/86681870/284898517-aa3a0fcd-8cfe-44fd-93ba-197e79350125.png">
> Notice the fields `articleType` and `triggeredBy` are being sent in addition to the context.
> 
> Please consider adding these two fields to the metadata accepted by the `logCreateArticle` function added in this PR.

I would have to go verify, but I don't think we know the article type, do we? xD 
We used to have an option to specify the article type but we won't be able to have that in the HIP at least not yet.

2023-11-22 17:30 UTC, mmitiche commented on src/insight/insightClient.ts
> +    public logCreateArticle(createArticle: CreateArticleMetadata, metadata?: CaseMetadata) {
```suggestion
    public logCreateArticle(createArticleMetadata: CreateArticleMetadata, metadata?: CaseMetadata) {
```

2023-11-22 17:30 UTC, mmitiche commented on src/insight/insightClient.ts
> +            metadata ? {...generateMetadataToSend(metadata, false), ...createArticle} : {createArticle}
`createArticleMetadata` is already an object, we would get a different structure in the event custom data if we keep it `{createArticle}`
```suggestion
            metadata ? {...generateMetadataToSend(metadata, false), ...createArticle} : createArticle
```

2023-11-22 18:14 UTC, SimonMilord commented on src/insight/insightClient.ts
> +    public logCreateArticle(createArticle: CreateArticleMetadata, metadata?: CaseMetadata) {
I was using the same pattern as :

`logPageViewClick(pageView: UserActionsPageViewMetadata, metadata: CaseMetadata)`

but sure I can change it

2023-11-22 18:19 UTC, mmitiche approved these changes
LGTM 👌

2023-11-22 19:06 UTC, merged